### Постановка задачи
Заполним отсутствующие значения по погоде интерполяционными данными.

Для точки росы вычтем температуру воздуха, направление ветра разложим на синус и косинус, для температуры воздуха вычислим  первую и вторую производные. Также введем параметры по праздничным дням, дням недели, месяцам и неделям года.

Посчитаем модель линейной регрессии по первым 20 зданиям и найдем ее точность. Проверим, какой набор параметров позволяет улучшить точность.

Данные:
* http://video.ittensive.com/machine-learning/ashrae/building_metadata.csv.gz
* http://video.ittensive.com/machine-learning/ashrae/weather_train.csv.gz
* http://video.ittensive.com/machine-learning/ashrae/train.0.csv.gz
Соревнование: https://www.kaggle.com/c/ashrae-energy-prediction/

© ITtensive, 2020

### Подключение библиотек

In [1]:
import pandas as pd
from pandas.tseries.holiday import USFederalHolidayCalendar as calendar
import numpy as np
from scipy.interpolate import interp1d
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression

### Загрузка данных, отсечение 20 зданий, объединение и оптимизация

In [2]:
def reduce_mem_usage (df):
    start_mem = df.memory_usage().sum() / 1024**2    
    for col in df.columns:
        col_type = df[col].dtypes
        if str(col_type)[:5] == "float":
            c_min = df[col].min()
            c_max = df[col].max()
            if c_min > np.finfo("f2").min and c_max < np.finfo("f2").max:
                df[col] = df[col].astype(np.float16)
            elif c_min > np.finfo("f4").min and c_max < np.finfo("f4").max:
                df[col] = df[col].astype(np.float32)
            else:
                df[col] = df[col].astype(np.float64)
        elif str(col_type)[:3] == "int":
            c_min = df[col].min()
            c_max = df[col].max()
            if c_min > np.iinfo("i1").min and c_max < np.iinfo("i1").max:
                df[col] = df[col].astype(np.int8)
            elif c_min > np.iinfo("i2").min and c_max < np.iinfo("i2").max:
                df[col] = df[col].astype(np.int16)
            elif c_min > np.iinfo("i4").min and c_max < np.iinfo("i4").max:
                df[col] = df[col].astype(np.int32)
            elif c_min > np.iinfo("i8").min and c_max < np.iinfo("i8").max:
                df[col] = df[col].astype(np.int64)
        elif col == "timestamp":
            df[col] = pd.to_datetime(df[col])
        elif str(col_type)[:8] != "datetime":
            df[col] = df[col].astype("category")
    end_mem = df.memory_usage().sum() / 1024**2
    print('Потребление памяти меньше на', round(start_mem - end_mem, 2), 'Мб (минус', round(100 * (start_mem - end_mem) / start_mem, 1), '%)')
    return df

In [3]:
buildings = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/building_metadata.csv.gz")
weather = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/weather_train.csv.gz")
weather = weather[weather["site_id"] == 0]
energy = pd.read_csv("http://video.ittensive.com/machine-learning/ashrae/train.0.csv.gz")
energy = energy[energy["building_id"]<20]
energy = pd.merge(left=energy, right=buildings, how="left",
                   left_on="building_id", right_on="building_id")
del buildings
print (energy.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 175680 entries, 0 to 175679
Data columns (total 9 columns):
 #   Column         Non-Null Count   Dtype  
---  ------         --------------   -----  
 0   building_id    175680 non-null  int64  
 1   meter          175680 non-null  int64  
 2   timestamp      175680 non-null  object 
 3   meter_reading  175680 non-null  float64
 4   site_id        175680 non-null  int64  
 5   primary_use    175680 non-null  object 
 6   square_feet    175680 non-null  int64  
 7   year_built     175680 non-null  float64
 8   floor_count    0 non-null       float64
dtypes: float64(3), int64(4), object(2)
memory usage: 13.4+ MB
None


### Интерполяция значений

In [5]:
weather["precip_depth_1_hr"] = weather["precip_depth_1_hr"].apply(lambda x:x if x>0 else 0)
interpolate_columns = ["air_temperature", "dew_temperature",
                       "cloud_coverage", "wind_speed", "wind_direction",
                       "precip_depth_1_hr", "sea_level_pressure"]
for col in interpolate_columns:
    weather[col] = weather[col].interpolate(limit_direction='both',
                            kind='cubic')

### Обогащение данных: погода

In [6]:
weather["wind_direction_rad"] = weather["wind_direction"] * np.pi/180
weather["wind_direction_sin"] = np.sin(weather["wind_direction_rad"])
weather["wind_direction_cos"] = np.cos(weather["wind_direction_rad"])
weather["air_temperature_diff1"] = weather["air_temperature"].diff()
weather.at[0, "air_temperature_diff1"] = weather.at[1, "air_temperature_diff1"]
weather["air_temperature_diff2"] = weather["air_temperature_diff1"].diff()
weather.at[0, "air_temperature_diff2"] = weather.at[1, "air_temperature_diff2"]

### Объдинение погодных данных

In [7]:
energy = energy.set_index(["timestamp", "site_id"])
weather = weather.set_index(["timestamp", "site_id"])
energy = pd.merge(left=energy, right=weather, how="left",
                  left_index=True, right_index=True)
energy.reset_index(inplace=True)
energy = energy.drop(columns=["meter", "site_id", "year_built",
                              "square_feet", "floor_count"], axis=1)
del weather
energy = reduce_mem_usage(energy)
print (energy.info())

Потребление памяти меньше на 15.41 Мб (минус 71.9 %)
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 175680 entries, 0 to 175679
Data columns (total 16 columns):
 #   Column                 Non-Null Count   Dtype         
---  ------                 --------------   -----         
 0   timestamp              175680 non-null  datetime64[ns]
 1   building_id            175680 non-null  int8          
 2   meter_reading          175680 non-null  float16       
 3   primary_use            175680 non-null  category      
 4   air_temperature        175680 non-null  float16       
 5   cloud_coverage         175680 non-null  float16       
 6   dew_temperature        175680 non-null  float16       
 7   precip_depth_1_hr      175680 non-null  float16       
 8   sea_level_pressure     175680 non-null  float16       
 9   wind_direction         175680 non-null  float16       
 10  wind_speed             175680 non-null  float16       
 11  wind_direction_rad     175680 non-null  float16    

### Обогащение данных: дата

In [8]:
energy["hour"] = energy["timestamp"].dt.hour.astype("int8")
energy["weekday"] = energy["timestamp"].dt.weekday.astype("int8")
energy["week"] = energy["timestamp"].dt.week.astype("int8")
energy["month"] = energy["timestamp"].dt.month.astype("int8")
energy["date"] = pd.to_datetime(energy["timestamp"].dt.date)
dates_range = pd.date_range(start='2015-12-31', end='2017-01-01')
us_holidays = calendar().holidays(start=dates_range.min(),
                                  end=dates_range.max())
energy['is_holiday'] = energy['date'].isin(us_holidays).astype("int8")
for weekday in range(0,7):
    energy['is_wday' + str(weekday)] = energy['weekday'].isin([weekday]).astype("int8")
for week in range(1,54):
    energy['is_w' + str(week)] = energy['week'].isin([week]).astype("int8")
for month in range(1,13):
    energy['is_m' + str(month)] = energy['month'].isin([month]).astype("int8")

/tmp/ipykernel_426/3902833704.py:3: FutureWarning: Series.dt.weekofyear and Series.dt.week have been deprecated. Please use Series.dt.isocalendar().week instead.
  energy["week"] = energy["timestamp"].dt.week.astype("int8")


### Логарифмирование данных
z = A * x + B * y -> log z = A * x + B * y => z = e^Ax * e^By => z = a^x * b^y

In [9]:
energy["meter_reading_log"] = np.log(energy["meter_reading"] + 1)

### Разделение данных

In [10]:
energy_train, energy_test = train_test_split(energy[energy["meter_reading"]>0], test_size=0.2)
print (energy_train.info())

<class 'pandas.core.frame.DataFrame'>
Int64Index: 86858 entries, 120656 to 167777
Data columns (total 95 columns):
 #   Column                 Non-Null Count  Dtype         
---  ------                 --------------  -----         
 0   timestamp              86858 non-null  datetime64[ns]
 1   building_id            86858 non-null  int8          
 2   meter_reading          86858 non-null  float16       
 3   primary_use            86858 non-null  category      
 4   air_temperature        86858 non-null  float16       
 5   cloud_coverage         86858 non-null  float16       
 6   dew_temperature        86858 non-null  float16       
 7   precip_depth_1_hr      86858 non-null  float16       
 8   sea_level_pressure     86858 non-null  float16       
 9   wind_direction         86858 non-null  float16       
 10  wind_speed             86858 non-null  float16       
 11  wind_direction_rad     86858 non-null  float16       
 12  wind_direction_sin     86858 non-null  float16       


### Линейная регрессия
Постройте (1) первый набор моделей линейной регрессии по часам для каждого из первых 20 зданий по следующим параметрам: air_temperature, dew_temperature, cloud_coverage, wind_speed, sea_level_pressur
Используйте логарифм целевого показателя (meter_reading_log)

In [27]:
hours = range(0, 24)
buildings = range(0, energy_train["building_id"].max() + 1)
lr_columns = ["meter_reading_log", "hour", "building_id",
             "air_temperature", "dew_temperature",
             "sea_level_pressure", "wind_speed", "cloud_coverage"]
energy_train_lr = pd.DataFrame(energy_train, columns=lr_columns)
energy_lr = [[]]*len(buildings)
for building in buildings:
    energy_lr[building] = [[]]*len(hours)
    energy_train_b = energy_train_lr[energy_train_lr["building_id"]==building]
    for hour in hours:
        energy_train_bh = energy_train_b[energy_train_b["hour"]==hour]
        y = energy_train_bh["meter_reading_log"]
        x = energy_train_bh.drop(labels=["meter_reading_log",
            "hour", "building_id"], axis=1)
        model = LinearRegression(fit_intercept=False).fit(x, y)
        energy_lr[building][hour] = model.coef_
        energy_lr[building][hour] = np.append(energy_lr[building][hour], model.intercept_)

In [28]:
energy_lr[0]

[array([ 0.02063577,  0.01509997,  0.00457486, -0.00474737, -0.00093087,
         0.        ]),
 array([ 0.02746582,  0.00966712,  0.00458852, -0.01068523, -0.00941624,
         0.        ]),
 array([ 0.02558667,  0.01443124,  0.0045142 , -0.00073359, -0.00545515,
         0.        ]),
 array([ 0.02734158,  0.01125651,  0.00455897, -0.00791499, -0.00429899,
         0.        ]),
 array([ 0.04130215, -0.00454213,  0.00455431, -0.01252856, -0.00358451,
         0.        ]),
 array([ 0.03732583, -0.00054609,  0.00460303, -0.00767681, -0.01138811,
         0.        ]),
 array([ 0.04255417, -0.00577607,  0.00456639,  0.00184072, -0.00738641,
         0.        ]),
 array([ 0.03325161,  0.00266987,  0.0046397 ,  0.0001756 , -0.01154369,
         0.        ]),
 array([ 0.04027188, -0.00310843,  0.00462602, -0.00705059, -0.00948981,
         0.        ]),
 array([ 0.05678218, -0.02132418,  0.00456905, -0.00962738,  0.00256617,
         0.        ]),
 array([ 0.0621974 , -0.02739395,  0.004

### Расчет качества

In [29]:
def calculate_model (x):
    lr = -1
    model = energy_lr[x.building_id][x.hour]
    if len(model) > 0:
        lr = np.sum([x[col] * model[i] for i,col in enumerate(lr_columns[3:])])
        lr += model[len(lr_columns)-3]
        lr = np.exp(lr)
    if lr < 0:
        lr = 0
    x["meter_reading_lr_q"] = (np.log(x.meter_reading + 1) -
                               np.log(1 + lr))**2
    return x

energy_test = energy_test.apply(calculate_model,
                                    axis=1, result_type="expand")
energy_test_lr_rmsle = np.sqrt(energy_test["meter_reading_lr_q"].sum() / len(energy_test))
print ("Качество линейной регрессии, 20 зданий:",
       energy_test_lr_rmsle, round(energy_test_lr_rmsle, 1))

Качество линейной регрессии, 20 зданий: 0.23118936964202105 0.2


Постройте для этих же 20 зданий (2) второй набор моделей линейной регрессии по часам по параметрам: дни недели и праздники (is_holiday).

In [31]:
hours = range(0, 24)
buildings = range(0, energy_train["building_id"].max() + 1)
lr_columns_2 = ["meter_reading_log", "hour", "building_id",
             "weekday", "is_holiday"]
energy_train_lr_2 = pd.DataFrame(energy_train, columns=lr_columns_2)
energy_lr_2 = [[]]*len(buildings)
for building in buildings:
    energy_lr_2[building] = [[]]*len(hours)
    energy_train_b_2 = energy_train_lr_2[energy_train_lr_2["building_id"]==building]
    for hour in hours:
        energy_train_bh_2 = energy_train_b_2[energy_train_b_2["hour"]==hour]
        y = energy_train_bh_2["meter_reading_log"]
        x = energy_train_bh_2.drop(labels=["meter_reading_log",
            "hour", "building_id"], axis=1)
        model_2 = LinearRegression(fit_intercept=False).fit(x, y)
        energy_lr_2[building][hour] = model_2.coef_
        energy_lr_2[building][hour] = np.append(energy_lr_2[building][hour], model_2.intercept_)

In [32]:
energy_lr_2[0]

[array([1.22696839, 4.33639404, 0.        ]),
 array([1.25497522, 3.6633472 , 0.        ]),
 array([1.23085163, 3.61821397, 0.        ]),
 array([1.24537651, 3.87388366, 0.        ]),
 array([1.25020416, 3.83569931, 0.        ]),
 array([1.23138522, 3.6088732 , 0.        ]),
 array([1.24364359, 3.13807685, 0.        ]),
 array([1.24588338, 5.4296875 , 0.        ]),
 array([1.24544994, 3.74695217, 0.        ]),
 array([1.22691469, 4.60916369, 0.        ]),
 array([1.21907854, 3.95143962, 0.        ]),
 array([1.2520739 , 3.58225279, 0.        ]),
 array([1.23094754, 3.52042344, 0.        ]),
 array([1.2401429, 3.8591562, 0.       ]),
 array([1.25071556, 3.57009197, 0.        ]),
 array([1.25478687, 4.05673657, 0.        ]),
 array([1.2175692 , 3.83471093, 0.        ]),
 array([1.23885782, 3.8893013 , 0.        ]),
 array([1.22764718, 3.91279704, 0.        ]),
 array([1.26300413, 4.10418337, 0.        ]),
 array([1.23897759, 4.52297327, 0.        ]),
 array([1.24673218, 3.86774474, 0.   

In [40]:
def calculate_model_2 (x):
    lr = -1
    model = energy_lr_2[x.building_id][x.hour]
    if len(model) > 0:
        lr = np.sum([x[col] * model[i] for i,col in enumerate(lr_columns_2[3:])])
        lr += model[len(lr_columns_2)-3]
        lr = np.exp(lr)
    if lr < 0:
        lr = 0
    x["meter_reading_lr_q"] = (np.log(x.meter_reading + 1) -
                               np.log(1 + lr))**2
    return x

In [41]:
energy_test = energy_test.apply(calculate_model_2,
                                    axis=1, result_type="expand")
energy_test_lr_rmsle = np.sqrt(energy_test["meter_reading_lr_q"].sum() / len(energy_test))
print ("Качество линейной регрессии, 20 зданий:",
       energy_test_lr_rmsle, round(energy_test_lr_rmsle, 1))

Качество линейной регрессии, 20 зданий: 2.951249940483002 3.0
